version: '0.1'

services:
  postgres:
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - $PWD/tmp/sockets:/var/run/postgresql
    image: postgres:14.1
    user: postgres
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=education_project_ads_development
    healthcheck:
      test: ["CMD", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
  web:
    container_name: web
    build: .
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    command: /bin/sh -c "rm -f /rails/tmp/pids/server.pid && rails s -b 0.0.0.0 -p 3000"
    links:
      - postgres
    volumes:
      - $PWD/tmp/sockets:/var/run/postgresql
    environment:
      - DATABASE_PORT=5432
      - POSTGRES_USER=postgres
      - EDUCATION_PROJECT_ADS_DATABASE_PASSWORD=mysecretpassword
      - RAILS_ENV=development
      - RACK_ENV=development
      - MAIL_HOST='gmail.com'
      - SENDMAIL_USERNAME='itnews68@gmail.com'
      - SENDMAIL_PASSWORD=ItNews123456