default: &default
  password: somepass
  host: postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: postgres
  password: <%= ENV.fetch('EDUCATION_PROJECT_ADS_DATABASE_PASSWORD') { 'mysecretpassword' } %>
  timeout: 5000
  # url: <%= ENV['DATABASE_URL'] %>
  # socket: /tmp/.s.PGSQL.5432
development:
  <<: *default
  database: education_project_ads_development
test:
  <<: *default
  database: education_project_ads_test
production:
  <<: *default
  database: education_project_ads_production
